
[font]
size = 12.0

[font.bold]
family = "Fira Code"

[font.bold_italic]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"

[window.padding]
x = 5
y = 5

[general]

live_config_reload = true
import = ["~/.config/alacritty/colors/colors.toml"]
