[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#586899"
blue = "#36ACFC"
cyan = "#30E1C7"
green = "#64D464"
magenta = "#CEB5FD"
red = "#FDA7C1"
white = "#F5F6FB"
yellow = "#FCB173"

[colors.cursor]
cursor = "#BCC6E3"
text = "#FFFFFF"

[colors.dim]
black = "#171C2C"
blue = "#11387C"
cyan = "#146458"
green = "#1D5F0A"
magenta = "#5F4C7E"
red = "#7E3F54"
white = "#5E6371"
yellow = "#7B4B1C"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#FFFFFF"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#FFFFFF"

[colors.normal]
black = "#2E3859"
blue = "#1F6DF7"
cyan = "#28C8B1"
green = "#39BD14"
magenta = "#BD97FC"
red = "#FB80AA"
white = "#BCC6E3"
yellow = "#F49437"

[colors.primary]
background = "#1A2137"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#E7EBF6"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#FFFFFF"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#FFFFFF"

[colors.selection]
background = "#F5E0DC"
text = "#FFFFFF"

[colors.vi_mode_cursor]
cursor = "#BCC6E3"
text = "#FFFFFF"
